### ISSUE TITLE
PHP Warning:failed to open stream: Connection refused

### ISSUE THREAD

**Issue by Leslack-hub** [nizsheanez/yii2-json-rpc#11]
PHP Warning – yii\base\ErrorException
file_get_contents(http://admin.test.local): failed to open stream: Connection refused

**Comment by AskAlexSharov** [comment]
Not enough details to understand your problem: maybe your .local domain not configured, maybe you running PHP in Docker, maybe something else. Just do curl to that domain from same environment where your PHP working and fix that problem
